{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tokenshield.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  selector:
    app.kubernetes.io/name: postgres
{{- end }}
